### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by pp-jia** [Tjiawei/NeighborNet#2]
Has the author secure a job? When will the code be released?

**Comment by ExMorgan-Alter** [comment]
> Has the author secure a job? When will the code be released?

I haven't received an offer yet. The code is expected to be released at the end of September.

**Comment by ExMorgan-Alter** [comment]
> Has the author secure a job? When will the code be released?
The model code has been made public. The data preprocessing, training code, and trained model are expected to be made public by the end of September.
