### ISSUE TITLE
About preparing the dataset

### ISSUE THREAD

**Issue by KJWQYY** [Tjiawei/NeighborNet#3]
It is nice to discuss with you. I encountered some problems when running your work.
dataloader/supervise_movienet.py reads the data label and hop attributes from lines 23 to 30. The pkl file in sample_20 you provided in Generate Graph Files only has the hop attribute, and an error will be reported when reading the data and label attributes at runtime. In addition, how to obtain the hop attribute is not mentioned in the project. It would be great if you could publicly use a tool to obtain the hop attribute in your project. Finally, is the data attribute the data attribute of the pkl in VSMBD?

**Comment by ExMorgan-Alter** [comment]
> It is nice to discuss with you. I encountered some problems when running your work. dataloader/supervise_movienet.py reads the data label and hop attributes from lines 23 to 30. The pkl file in sample_20 you provided in Generate Graph Files only has the hop attribute, and an error will be reported when reading the data and label attributes at runtime. In addition, how to obtain the hop attribute is not mentioned in the project. It would be great if you could publicly use a tool to obtain the hop attribute in your project. Finally, is the data attribute the data attribute of the pkl in VSMBD?

Thank you for your interest in this project. Before running the code, generate the dataset by running gen_dataSet in dataloader/supervise_movienet.py; ft_path is the path of ImageNet_shot.pkl extracted by VSMBD. lb_path is the path of the txt file provided by MovieNet. Each txt file name is the IMDB ID of each movie, in which each element marks whether each shot is the end shot (the last shot) of the scene; gph_path is the file path after the sample_20.rar I provided is unzipped.  I will provide how to generate sample_20.rar in early November. Please forgive me for not having time recently.

**Comment by ExMorgan-Alter** [comment]
The file in sample_20 corresponds to the sentence "N^{l}_{i} signifies the top-k similar shots to the shot-i within a time
window centered on the shot i with a length of l." （In the lower part of Eq.(1)）

**Comment by KaiJiangSpace** [comment]
> The file in sample_20 corresponds to the sentence "N^{l}_{i} signifies the top-k similar shots to the shot-i within a time window centered on the shot i with a length of l." （In the lower part of Eq.(1)）

Thanks for your answer, it helps me a lot.

**Comment by KJWQYY** [comment]
> The file in sample_20 corresponds to the sentence "N^{l}_{i} signifies the top-k similar shots to the shot-i within a time window centered on the shot i with a length of l." （In the lower part of Eq.(1)）
Thank you for your answer, it is very helpful to me. I hope to continue to discuss NeighborNet with you in the future.
