### ISSUE TITLE
How to generate sample_20?

### ISSUE THREAD

**Issue by dbcoral7** [Tjiawei/NeighborNet#4]
Thanks for your work:)
I have a problem when doing inference on a new custom dataset.
Could you explain more about how to create sample_20? I know you discussed this in another issue, but if it seems like it will be delayed, I would appreciate it if you could explain it in writing.

**Comment by ExMorgan-Alter** [comment]
The file in sample_20 corresponds to the sentence "N^{l}_{i} signifies the top-k similar shots to the shot-i within a time
window centered on the shot i with a length of l." （In the lower part of Eq.(1)）


> Thanks for your work:) I have a problem when doing inference on a new custom dataset. Could you explain more about how to create sample_20? I know you discussed this in another issue, but if it seems like it will be delayed, I would appreciate it if you could explain it in writing.

**Comment by ExMorgan-Alter** [comment]
The following topKNN is the program that generates the graph.

---
```
def topKNN(feat:np.ndarray, win_size=5, top=5):
    # feat: (T, dim), T is 20, dim is feature dimension
    #  win_size: int, length L in eq.(1)
    #  top: top-k
    # simat: (T, top)
    T = feat.shape[0]
    temp_mask = np.zeros((T, T))

    for i in range(T):
        if i-win_size < 0:
            i_ser = [0, win_size*2]
        elif i+win_size >= T:
            i_ser = [T-2*win_size, T]
        else:
            i_ser = [i-win_size, i+win_size+1]
        temp_mask[i, i_ser[0]:i_ser[1]] = 1

    simat = similarity(feat, feat, temp_mask)
    simat = np.argsort(simat, axis=-1)[:, -1:-(top+1):-1]
    return simat
```


```
def normalized(a, axis=-1, order=2):
    l2 = np.atleast_1d(np.linalg.norm(a, order, axis))
    l2[l2==0] = 1
    return a / np.expand_dims(l2, axis)
```


```
def similarity(feat1, feat2, tmask=None):
    feat1 = normalized(feat1)
    feat2 = normalized(feat2)
    mat = np.matmul(feat1, feat2.transpose(1, 0))
    mask = np.eye(feat1.shape[0])
    mat = mat - mask
    if tmask is not None:
        mat = mat * tmask

    return mat
```

> Thanks for your work:) I have a problem when doing inference on a new custom dataset. Could you explain more about how to create sample_20? I know you discussed this in another issue, but if it seems like it will be delayed, I would appreciate it if you could explain it in writing.

**Comment by A-Rush-R** [comment]
Hi

We used your code to generate sample_20 file and train the model, however we were getting very poor results, could you please provide an alternate link for the sample_20 file? And the training hyperparametres if possible? Thank You

**Comment by KarineAyrs** [comment]
@ExMorgan-Alter can you explain this line `simat = np.argsort(simat, axis=-1)[:, -1:-(top+1):-1]` it gives an error
